"""
Docker image builder — generates Dockerfiles from manifest environment specs.

Each GPU/high-memory tool gets its own Docker image with isolated dependencies.
GPU tools use nvidia/cuda base images; CPU-only tools use python:slim.
"""

import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger("ct.cloud.image_builder")


def generate_dockerfile(tool_config: dict) -> str:
    """Generate a Dockerfile from a tool's manifest configuration.

    Args:
        tool_config: Tool configuration dict from the manifest.

    Returns:
        Dockerfile content as a string.
    """
    env = tool_config.get("environment", {})
    hw = tool_config.get("hardware", {})
    display_name = tool_config.get("display_name", "unknown")

    cpu_only = hw.get("cpu_only", False)
    python_version = env.get("python", "3.11")

    # Select base image
    if cpu_only:
        base_image = env.get("base", f"python:{python_version}-slim")
    else:
        cuda_version = env.get("cuda", "12.1")
        base_image = env.get("base", f"nvidia/cuda:{cuda_version}.0-runtime-ubuntu22.04")

    lines = [
        f"# Auto-generated Dockerfile for {display_name}",
        "# DO NOT EDIT — generated by image_builder.py",
        f"FROM {base_image}",
        "",
        "# Prevent interactive prompts during build",
        'ENV DEBIAN_FRONTEND=noninteractive',
        "",
    ]

    # Install system packages
    apt_packages = env.get("apt", [])
    if apt_packages or not cpu_only:
        # GPU images need python installed
        system_pkgs = list(apt_packages)
        if not cpu_only:
            system_pkgs = [f"python{python_version}", f"python{python_version}-venv", "python3-pip"] + system_pkgs

        if system_pkgs:
            pkg_str = " \\\n    ".join(system_pkgs)
            lines.extend([
                "RUN apt-get update && apt-get install -y --no-install-recommends \\",
                f"    {pkg_str} \\",
                "    && rm -rf /var/lib/apt/lists/*",
                "",
            ])

        # Symlink python if on GPU image
        if not cpu_only:
            lines.extend([
                f"RUN ln -sf /usr/bin/python{python_version} /usr/bin/python",
                "",
            ])

    # Install conda packages (if any)
    conda_packages = env.get("conda", [])
    if conda_packages:
        pkg_str = " ".join(conda_packages)
        lines.extend([
            "# Install conda packages",
            f"RUN conda install -y {pkg_str}",
            "",
        ])

    # Install git if git_repos are needed
    git_repos = env.get("git_repos", [])
    if git_repos:
        lines.extend([
            "RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*",
            "",
        ])

    # Install pip packages
    pip_packages = env.get("pip", [])
    if pip_packages:
        pkg_str = " \\\n    ".join(pip_packages)
        lines.extend([
            "RUN python -m pip install --no-cache-dir \\",
            f"    {pkg_str}",
            "",
        ])

    # Clone git repositories
    for repo in git_repos:
        url = repo.get("url", "")
        target = repo.get("target", "/opt/repo")
        branch = repo.get("branch", "")
        branch_flag = f" -b {branch}" if branch else ""
        lines.extend([
            f"RUN git clone --depth 1{branch_flag} {url} {target}",
            "",
        ])

    # Set environment variables
    env_vars = env.get("env_vars", {})
    if env_vars:
        for key, value in env_vars.items():
            lines.append(f"ENV {key}={value}")
        lines.append("")

    # Copy entrypoint and implementation
    lines.extend([
        "# Copy standard entrypoint",
        "COPY tool_entrypoint.py /opt/tool_entrypoint.py",
        "",
        "# Copy implementation",
        "COPY implementation.py /opt/implementation.py",
        "",
        "# Create workspace directory",
        "RUN mkdir -p /workspace",
        "WORKDIR /workspace",
        "",
        'ENTRYPOINT ["python", "/opt/tool_entrypoint.py"]',
        "",
    ])

    return "\n".join(lines)


def write_dockerfile(tool_config: dict, output_dir: Path) -> Path:
    """Generate and write a Dockerfile to the specified directory.

    Args:
        tool_config: Tool configuration dict from the manifest.
        output_dir: Directory to write the Dockerfile to.

    Returns:
        Path to the generated Dockerfile.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    dockerfile_path = output_dir / "Dockerfile"
    content = generate_dockerfile(tool_config)
    dockerfile_path.write_text(content)
    logger.info("Generated Dockerfile at %s", dockerfile_path)
    return dockerfile_path
